export const CREATION_UPDATE = "CREATION_UPDATE";
export const CREATION_NOT_FOUND = "CREATION_NOT_FOUND";
export const CREATION_SAVE_START = "CREATION_SAVE_START";
export const CREATION_SAVE_SUCCESS = "CREATION_SAVE_SUCCESS";
export const CREATION_SAVE_ERROR = "CREATION_SAVE_ERROR";
export const CREATION_SET_TAG = "CREATION_SET_TAG";
export const CREATION_INICIALIZE = "CREATION_INICIALIZE";

export const CREATION_HTML_SET_SOURCE = "CREATION_HTML_SET_SOURCE";
export const CREATION_HTML_PREPROCESS_START = "CREATION_HTML_PREPROCESS_START";
export const CREATION_HTML_PREPROCESS_SUCCESS =
  "CREATION_HTML_PREPROCESS_SUCCESS";
export const CREATION_HTML_PREPROCESS_ERROR = "CREATION_HTML_PREPROCESS_ERROR";

export const CREATION_CSS_SET_SOURCE = "CREATION_CSS_SET_SOURCE";
export const CREATION_CSS_PREPROCESS_START = "CREATION_CSS_PREPROCESS_START";
export const CREATION_CSS_PREPROCESS_SUCCESS =
  "CREATION_CSS_PREPROCESS_SUCCESS";
export const CREATION_CSS_PREPROCESS_ERROR = "CREATION_CSS_PREPROCESS_ERROR";
export const CREATION_CSS_SET_PREPROCESSOR = "CREATION_CSS_SET_PREPROCESSOR";
